name: CI/CD Pipeline for SonarQube

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Configurer JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    # Étape 3 : Compiler et exécuter les tests
    - name: Build and test
      run: |
        ./gradlew build

    # Étape 4 : Analyser avec SonarQube
    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        ./gradlew sonarqube \
          -Dsonar.projectKey=sonarqube \
          -Dsonar.host.url=https://sonarqube.example.com \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
