name: CI/CD Pipeline for SonarQube

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permissions for Gradlew
        run: chmod +x ./gradlew

      - name: Build and test
        run: ./gradlew build

      - name: SonarQube Scan
        run: |
          docker pull sonarqube
          docker run -d --name sonarqube -p 9000:9000 sonarqube
